#!/usr/bin/bash

echo "Executing RELIANOID Cluster transtion to MASTER...\n"

# wait for 1 second to the first replication
sleep 1

# start RELIANOID service
systemctl start relianoid.service

# update cluster status
echo master > /etc/relianoid-ce-cluster.status

# start noid-cluster-notify
nohup /usr/local/relianoid/bin/noid-cluster-notify.pl >/dev/null 2>&1 &

