#! /usr/bin/perl
### BEGIN INIT INFO
# Provides:          relianoid
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: relianoid
# Description:
#
### END INIT INFO
###############################################################################
#
#    RELIANOID Software License
#    This file is part of the RELIANOID Load Balancer software package.
#
#    Copyright (C) 2014-today RELIANOID
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

use strict;
use warnings;

my $bin    = "/usr/local/relianoid/bin/relianoid";
my $action = $ARGV[0];

if ("$action" eq "start") {
    exit system "$bin start > /dev/console";
}

if ("$action" eq "stop") {
    exit system "$bin stop > /dev/console";
}

if ("$action" eq "restart") {
    system "$bin stop > /dev/console";
    sleep 5;
    exit system "$bin start > /dev/console";
}

print "Usage: /etc/init.d/relianoid ( stop | start | restart )\n";
