#!/usr/bin/perl
### BEGIN INIT INFO
# Provides:          relianoid-ce-cluster
# Required-Start:    relianoid
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: relianoid ce cluster service
# Description:
#
### END INIT INFO
###############################################################################
#
#    RELIANOID Software License
#    This file is part of the RELIANOID Load Balancer software package.
#
#    Copyright (C) 2014-today RELIANOID
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

my $action = $ARGV[0];

my $cluster_status_file = "/etc/relianoid-ce-cluster.status";

if ($action eq "start") {
    print "Starting RELIANOID CE Cluster...\n";
    require "/usr/local/relianoid/app/ucarp/etc/cluster.conf";
    my $command =
        "$ucarp -r ${dead_ratio} --interface=$interface --srcip=$local_ip --vhid=$cluster_id "
      . "--pass=$password --addr=$cluster_ip --upscript=$up_script --downscript=$down_script -B";
    my @run  = `$command`;
    my $exec = `nohup /usr/local/relianoid/bin/noid-cluster-notify.pl >/dev/null 2>&1 &`;
    exit;
}

if ($action eq "stop") {
    print "Stopping RELIANOID CE Cluster...\n";
    my $command = "pkill -9 ucarp ; kill -9 `pidof -x noid-cluster-notify.pl` 2>/dev/null";
    my @run     = `$command`;
    if (-e $cluster_status_file) {
        unlink $cluster_status_file;
    }
    exit;
}

print "Usage: /etc/init.d/relianoid-ce-cluster ( stop | start )\n";
