#!/usr/bin/perl
###############################################################################
#
#    RELIANOID Software License
#    This file is part of the RELIANOID Load Balancer software package.
#
#    Copyright (C) 2014-today RELIANOID
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

use strict;
use autodie;
use File::Copy;

### Zevenet to Relianoid
my $local_path = "/usr/local";
my $share_path = "/usr/share/perl5";
if (-d "${local_path}/zevenet" && !-l "${local_path}/zevenet") {
    rename "${local_path}/zevenet/config", "${local_path}/relianoid/config";
    if (-d "${local_path}/zevenet/backups") {
        rename "${local_path}/zevenet/backups", "${local_path}/relianoid/backups";
    }
    system "rm -rf ${local_path}/zevenet";
}

# create symlink for backups compatibility
if (!-e "${local_path}/zevenet") {
    symlink "relianoid", "${local_path}/zevenet";
}

if (-d "${share_path}/Zevenet" && !-l "${share_path}/Zevenet") {
    rename "${share_path}/Zevenet", "${share_path}/Relianoid";
    symlink "Relianoid", "${share_path}/Zevenet";
}
## Cluster CE
my $old_cluster_config = "/usr/local/relianoid/app/ucarp/etc/zevenet-cluster.conf";
my $new_cluster_config = "/usr/local/relianoid/app/ucarp/etc/cluster.conf";

if (-f $old_cluster_config) {
    rename "${old_cluster_config}", "${new_cluster_config}";
}

my $old_cluster_status = "/etc/zevenet-ce-cluster.status";
my $new_cluster_status = "/etc/relianoid-ce-cluster.status";

if (-f "${old_cluster_status}") {
    rename "${old_cluster_status}", "${new_cluster_status}";
    symlink "${new_cluster_status}", "${old_cluster_status}";
}
### Zevenet to Relianoid

exit 0;
