###############################################################################
#
#    ZEVENET Software License
#    This file is part of the ZEVENET Load Balancer software package.
#
#    Copyright (C) 2014-today ZEVENET SL, Sevilla (Spain)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################

FROM zevenet/zvn-builder-base:#{version}

# Base packages
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libperl-dev

# Use host user uid/gid, so the new files are owned by the user
# running the container
ARG host_uid
ARG host_gid

# The -o option (non-unique) is a hack that avoid problems when
# the image is built as root
RUN groupadd -o -g ${host_uid} host_user && \
    useradd  -o -u ${host_uid} -g ${host_gid} host_user
USER host_user
